apiVersion: policy.cert-manager.io/v1alpha1
kind: CertificateRequestPolicy
metadata:
  name: dsocc-int-dev-policy
spec:
  allowed:
    commonName:
      value: '*'
    dnsNames:
      values:
      - "*.mil"
    subject:
      organizations:
        values: ["DCOPS"]
      countries:
        values: ["*"]
      organizationalUnits:
        values: ["*"]
      localities:
        values: ["*"]
      provinces:
        values: ["*"]
      streetAddresses:
        values: ["*"]
      postalCodes:
        values: ["*"]
      serialNumber:
        value: "*"
  selector:
    issuerRef:
      kind: ClusterIssuer
      name: ca-issuer-itc
    namespace:
      matchNames:
      - istio-system
      - dsocc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-policy:dsocc-preprod
rules:
  - apiGroups: ["policy.cert-manager.io"]
    resources: ["certificaterequestpolicies"]
    verbs: ["use"]
    resourceNames: ["dsocc-preprod-policy"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-policy:dsocc-preprod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-policy:dsocc-preprod
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io